name: Eslint run
on: [push]
jobs:
  prep:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
      - name: checkout
        uses: actions/checkout@v1
      - name: install dependencies
        run: yarn install
      - name: lints
        uses: Krizzu/eslint-check-action@v1.0.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          eslintFiles: "src"
