name: Issues
on: [push]
jobs:
  triage_issues:
    name: Issue triage
    runs-on: ubuntu-latest
    steps:
      - name: Issue triage
        uses: Krizzu/issue-triage-action@v1.0.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          staleAfter: 1
          closeAfter: 3
          staleLabel: "STALE 📺"
          showLogs: true
